---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: tathagata
  become: false
  tasks:
    #    - name: Ensure Python3 and Pip are installed
    #      apt:
    #        name:
    #          - python3
    #          - python3-pip
    #        state: present
    #        update_cache: yes
    #
    #    - name: Install Docker Python SDK
    #      pip:
    #        name: docker
    #        executable: pip3

    - name: Pull Docker Image
      docker_image:
        name: "tathagata125/calculator1"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started

    - name: Run Docker container
      docker_container:
        name: calculator
        image: tathagata125/calculator1
        state: started
        tty: true
        interactive: true
        detach: true
        command: java -jar MT2024161-1.0-SNAPSHOT.jar
