---
- name: Pull Docker Image from Docker Hub
  hosts: localhost #machine where the playbook will run
  remote_user: tathagata #username
  become: false #dont want playbook to run as root*
  tasks:


    - name: Pull Docker Image
      docker_image:
        name: "tathagata125/calculator2"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started

    - name: Run Docker container
      docker_container:
        name: calculator2
        image: tathagata125/calculator2
        state: started
        tty: true
        detach: true
        command: java -jar MT2024161-1.0-SNAPSHOT.jar
